#ifndef ENUM_DEFS_H
#define ENUM_DEFS_H

enum CollisionState { NONE_COLLIDED, PLAYER1_COLLIDED, PLAYER2_COLLIDED, BOTH_COLLIDED };
enum InputState { NO_PROCESSED, PLAYER1_PROCESSED, PLAYER2_PROCESSED, BOTH_PROCESSED };
enum TipoCasilla {
    FREE,
    WALL
};

#endif
